apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhtap-logging
  namespace: openshift-gitops-operator
spec:
  source:
    repoURL: https://github.com/eisraeli/logging-dev.git
    targetRevision: RHTAPWATCH-499
  project: rhtap-logging
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
